import type { Metadata } from "next";
import "./globals.css";
import MainNav from "../components/navbar/MainNav";

export const metadata: Metadata = {
  title: "Bandar Musik Jakarta BMJ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={"font-poppins antialiased"}>
        <MainNav/>
        <div className="wrap">
          {children}
        </div>
      </body>
    </html>
  );
}
