import type { Metadata } from "next";
import "./globals.css";
import MainNav from "../components/navbar/MainNav";
import LayoutNav from "@/components/navbar/LayoutNav";
import Footer from "@/components/footer/MainFooter";

export const metadata: Metadata = {
  title: "Bandar Musik Jakarta BMJ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
          <link rel="dns-prefetch" href="https://server.bandarmusikjakarta.com" />
          <link rel="preconnect" href="https://server.bandarmusikjakarta.com" crossOrigin={'anonymous'} />
          <script defer src="https://analytics.bandarmusikjakarta.com/script.js" data-website-id="9b499a3d-a083-4aa8-8dbd-1a894483150c"></script>
      </head>


      <body className={"font-poppins antialiased"}>
        <LayoutNav/>
        <div className="wrap">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
